import type { Request, Response } from "express";
console.log("express OK");
import { prisma } from "./db.js";
console.log("db OK");
import type { AuthRequest } from "./middlewares/authenticate.middleware.js";
console.log("authenticate OK");
import bcrypt from "bcrypt";
console.log("bcrypt OK");
import { generateTempPassword } from "./utils/password.js";
console.log("password OK");
import { sendSchoolAdminCredentials } from "./utils/mailer.js";
console.log("mailer OK");
import { imagekit } from "./config/imagekit.js";
console.log("imagekit OK");
import ImageKit from "imagekit";
console.log("ImageKit OK");
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const { UserRole } = require("./generated/prisma/index.js");
console.log("Prisma enums OK");
console.log("ALL IMPORTS OK");
